export const CANDIDATE_LIST_REQUEST = 'CANDIDATE_LIST_REQUEST';
export const CANDIDATE_LIST_SUCCESS = 'CANDIDATE_LIST_SUCCESS';
export const CANDIDATE_LIST_FAIL = 'CANDIDATE_LIST_FAIL';

export const UPDATE_VOTE_COUNT_REQUEST = 'UPDATE_VOTE_COUNT_REQUEST';
export const UPDATE_VOTE_COUNT_SUCCESS = 'UPDATE_VOTE_COUNT_SUCCESS';
export const UPDATE_VOTE_COUNT_FAIL = 'UPDATE_VOTE_COUNT_FAIL';